# Generated by Django 5.0.6 on 2024-06-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('permis_conduire', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MarqueVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProprietaireVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_infraction', models.CharField(max_length=100)),
                ('date_infraction', models.DateField()),
                ('description', models.TextField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulier', models.BooleanField(default=False)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('immatriculation', models.CharField(max_length=100, unique=True)),
                ('date_achat', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(max_length=50)),
                ('puissance', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('date_assurance', models.DateField()),
                ('date_vidange', models.DateField()),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.marquevehicule')),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.proprietairevehicule')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.typevehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_panne', models.DateField()),
                ('nature_panne', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reparation', models.DateField(blank=True, null=True)),
                ('cout_reparation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('destination', models.CharField(max_length=200)),
                ('motif', models.TextField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('fournisseur', models.CharField(max_length=100)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField()),
                ('type_entretien', models.CharField(max_length=100)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_expiration', models.DateField()),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.typedocument')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.proprietairevehicule')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consommation', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometrage', models.IntegerField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accident', models.DateField()),
                ('circonstances', models.TextField()),
                ('dommages', models.TextField()),
                ('date_reparation', models.DateField(blank=True, null=True)),
                ('cout_reparation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeHome.conducteur')),
            ],
        ),
    ]
