# Generated by Django 5.0.6 on 2024-06-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('piece_identite', models.CharField(blank=True, max_length=100, null=True)),
                ('permis_conduire', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proprietairevehicule',
            name='email',
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='avec_chauffeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.conducteur'),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='client',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='safeHome.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='type_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.typemission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='type_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safeHome.typemission'),
        ),
    ]
