# Generated by Django 5.0.6 on 2024-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeHome', '0002_client_typemission_remove_conducteur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fichierpermis_conduire',
            field=models.FileField(blank=True, null=True, upload_to='documentsoi/'),
        ),
        migrations.AddField(
            model_name='client',
            name='fichierpiece_identite',
            field=models.FileField(blank=True, null=True, upload_to='documentso/'),
        ),
    ]
